### ISSUE TITLE
Example page: Cursor moves to the end when user starts typing

### ISSUE THREAD

**Issue by papas-source** [WebReflection/hyperHTML-Element#1]
Hello there, 

At the [example page](https://webreflection.github.io/hyperHTML-Element/test/)  if you put the cursor inside the text box - not at the end but between two characters - and you start typing, the cursor moves to the end.

I believe this is something nobody wants to happen. I understand that it may not actually be an issue in `hyperHTML-Element` - could be poor implementation or a bug in  `HyperHTML`, I don't really have time to look into it right now - but I just thought I should report it.

(for the record, its Chrome 59.0.3071.115 on MacOSX
Cheers

**Comment by WebReflection** [comment]
The test page was using 0.17.2 and the issue was fixed in 0.17.3.

I've updated the test page with latest 0.17.4 and everything should work.

**Comment by WebReflection** [comment]
Btw, yest, it was `hyperHTML` and **not** `HyperHTMLElement` gotcha and only on Safari, not sure why your Chrome had same issue, yet it's fixed anyway.

**Comment by papas-source** [comment]
I can confirm it is fixed. I also remember this was reported as an issue in `hyperHTML` ;)

Thanks for your great work!
