### ISSUE TITLE
Could it be used with document-register-element on old browsers?

### ISSUE THREAD

**Issue by zwz** [WebReflection/hyperHTML-Element#11]
I saw "document-register-element", another repo of yours, a polyfill of custom element.
So I came up this question. If the answer is `yes`, it should be mentioned in the README.

**Comment by WebReflection** [comment]
I think the little [compatibility section](https://github.com/WebReflection/hyperHTML-Element#compatibility) already covers this?

**Comment by zwz** [comment]
But if the polyfill works, is it compatible with IE9+?

**Comment by WebReflection** [comment]
the polyfill works already but for properly transpiled classes you need IE11 or greater.
