### ISSUE TITLE
Observation: self-closing custom tags

### ISSUE THREAD

**Issue by AutoSponge** [WebReflection/hyperHTML-Element#14]
Not sure if this is a bug or known issue.

When using self-closing custom tags, only the first one renders. For example, using the [codepen](https://codepen.io/WebReflection/pen/yoPNaz?editors=0010), change the `innerHTML` line to this:

```js
document.body.innerHTML =
  '<my-component name="First"/><my-component name="Third"/>';
```

I would expect to see "Hello, First Hello, Third Hello, Second" but instead only see "First" and "Second".

**Comment by WebReflection** [comment]
that's how HTML works. `hyperHTML` is based on standards, not JSX
