### ISSUE TITLE
IE bug ?

### ISSUE THREAD

**Issue by bigopon** [WebReflection/hyperHTML-Element#2]
IE version: 11

I got the following errors when trying the test page (transpiled version):

![](https://lh3.googleusercontent.com/Hkgbua6ikcZubWTySBWskcru2-ghQREfFQ6rQUFfK2c2OB-R0Dd0SwPO7aZ7V31VUy8OignnKZ7O7RXFhSfvDQLJd5wHnDmaCNlSK_NgbIxAWs6VOyjcS4coUXHgElIN5OIURGjFNf2WeIcdhZQALAQ29D94sY2T4JMvuCYf063-s25rYlJdJnqbECAH7n19nVzi9nLWr1E51Zdp-HY8d4_XtjNgq8tG3qsCPCf9vPf9xEUaQJWx1clQyjohKr3_DzdASEHkobTsKJvsqXDeTcj2-8iKeT8zoID160U0Cyc3V25In_938UfwKmww5hEdGel9d-nxigZblC1uL-sLHGQQBAcBzNYgwpjPGfqJ2tqa0J3jKQRWwMuBYBqFGEYdyACRk8beTgtrJofppfgiM3AguVwsVfGPOeP0LjAXtQ-ZYnh37vRkDxZ18QGTBx3w2BCEvltII5yE9zhCML6rjChjWCutDtFf1VzQnFEAdzR5GDsgec4lZTBPJh-RCkRzptXmf6yQwHZdsDcXeMhUQN7YrNEHU4VChKPzDlv8mvA6n2V-8StR9BPpiuyyagK6mcRCKmsBx_23hWgWoUcvBxl7cPU3loLr04SIJ8kvM-9SdzTyQ7z_2Qo-=w976-h295-no)

Here is the source part:

![](https://lh3.googleusercontent.com/S11ixadqycG4WWTzGwYCav8eiYtY1lx-xrx_XNfh7796hEU5YtyHxX0Q-Pu04pmB7NDwQBG8-SCdQ5gmw9lXPnrcwOX_LxNP04pyWIkZKsNSYktVxb7FhE4U8FKqdoLUBFySGYtYUE2v9RnvpvYPwQPGgyK_MoRZQnByh8PV-Lc9oIkS9WDHjpD4VYeXqP58_ZdBGv4fM5BI5dAfYn6226JCf3W2KIp07HhOEcSGbJ70L3yh8VjpHxU7FHVfVKbhVuXemA3ISNKAaOioMuCCShIVUyWgMNPLL5uHwJt7r_ObceDyAMUnTj7JdVuzpLnh-gH7uE20o2ouvAQMWHiXMI7OTXRNEj4cShWXAFsdIlX19G-Awb5DMrTWxF9dftJM9N3WLOgwSK83X4Yyd5Lj8-9_KqPHfXgWpu4y092pkj4BBYikOXszhuj89eTLszI9zE57Si6HH3DmkqadDmhd6ZLyrqAS0WkpHM76hKkcHDB64KQVN7Xq1gJVIMUA1G_ddBdSvn-XdsSm7qNc1gpKICspuxyqKb9fIUJNfkfJa_m09g4vQ9fvyTRdwlOIl7HHBfCPLIluQTue6k4u7DwpvYEcFjo17CHrW2WVkkSkDxhj4UptI8FAc2jw=w492-h356-no)

**Comment by WebReflection** [comment]
Under attack from all fronts :laughing: 

https://github.com/WebReflection/babel-plugin-transform-builtin-classes/issues/1

will have a look, IE11 supposed to be a valid target.

**Comment by WebReflection** [comment]
`v0.2.2` fixed this issue
