### ISSUE TITLE
stores support (mobx/subscriptions)

### ISSUE THREAD

**Issue by janat08** [WebReflection/hyperHTML-Element#20]
Would it be possible to enable support for stores and even subscriptions are hyper-element does: https://github.com/codemeasandwich/hyper-element?

**Comment by WebReflection** [comment]
there is a state management with a default state, isn't that enough?

About event subscriptions, not sure what you mean ... you can add pretty much every event you want through the `on` prefix as in `<p oneventname=${callback}>`

Last, if you think hyper-element is a better solution just use it instead. It's a cool parallel solution, not something I want replace or keep track to make this one identical 😉

**Comment by janat08** [comment]
As in live data subscriptions (meteor/firebase/websocket stuff) that should close once the component is gone.  It is not a better solution, it's pretty much the feature I'm after, to me it came across bugged. Mobx  acts as a separation of concerns and autorun make binding backend to frontend a bliss. The attrs interface isn't the best at all.

**Comment by janat08** [comment]
I would settle for component destroyed hook and instructions explaining how to integrate these things.

**Comment by janat08** [comment]
``` js
  const next = onNext();
  const ws = new WebSocket("ws://127.0.0.1/data");

  ws.onmessage = ({data}) => next(JSON.parse(data))

  // Return way to unsubscribe
  const teardown = ws.close.bind(ws);
  return teardown
```
Basically without teardown server will continue trying to push data to the client that's not listening.
