### ISSUE TITLE
asynchronous rendering

### ISSUE THREAD

**Issue by phryniszak** [WebReflection/hyperHTML-Element#26]
Can you consider adding batched rendering like in lit-element?

**Comment by WebReflection** [comment]
have you even tried? it's supported since ever in hyperHTML too and viperHTML as well ... use a promise as interpolated value and call it a day 🎉

**Comment by phryniszak** [comment]
yes I tried, and you are right, but lit-element gives me this without any not natural code plumbing. Thanks anyway and don't forget about users

**Comment by WebReflection** [comment]
> lit-element gives me this without any not natural code plumbing

I don't know what you mean ... sorry

> Thanks anyway and don't forget about users

I didn't. Indeed the Promises / async capability was added as soon as users asked me to, and very long time ago, even on the SSR viperHTML side.

Not sure what else should I do.

**Comment by phryniszak** [comment]
I didn't explained.
Please have a look at this:
https://codepen.io/phryniszak/project/editor/AdGRpe
each component is rendered during construction and one time for each property.
Am I doing something wrong?
