### ISSUE TITLE
Multiple elements, only the first is rendered

### ISSUE THREAD

**Issue by davidmerrique** [WebReflection/hyperHTML-Element#3]
Hi, seems like multiple elements don't work.

```html
<custom-element></custom-element>
<custom-element></custom-element>
<custom-element></custom-element>
```

Only the first element is rendered.

https://codepen.io/davidmerrique/pen/XajWRQ?editors=1010

**Comment by WebReflection** [comment]
what a rookie error I've made ... will fix in a minute, thanks

**Comment by WebReflection** [comment]
Please use `0.2.1` thanks.
