### ISSUE TITLE
question: should hyperHTML support all build formats 

### ISSUE THREAD

**Issue by douglasduteil** [WebReflection/hyperHTML-Element#32]
\following #31

Hi @WebReflection

Actually, I have a more global question/comment to make as I'm trying to get HyperHTMLElement to play around with Webpack and IE11.

I proposed an UMD build (#31) because I  actually need an ESM + ES5 (=ESM5) build so Webpack and IE are happy...

What do you think about the multiplication of build formats from ESM2015, ESM5, FESM5, FESM2015, CJS to UMD ?

Do you think as a library you should support none, most or all of them ? 

\personaly 
I kind of feel like there is no end to the possible combinations so it might be better to look for a way to compile your ES6 code to whatever target I need. What you think ?

Douglas.

**Comment by WebReflection** [comment]
I think I never had issues with `require("hyperhtml-element/cjs")` or `import HyperHTMLElement from "hyperhtml-element/esm"`, if Webpack is your issue.
