### ISSUE TITLE
Latest version 2.1.1 sets value to true if passed an empty value to an attribute

### ISSUE THREAD

**Issue by pinguxx** [WebReflection/hyperHTML-Element#34]
See the example here
https://stackblitz.com/edit/js-mjkhqr?file=index.js

**Comment by WebReflection** [comment]
Please check the PR and let me know if that works.

**Comment by pinguxx** [comment]
i rather specifically add boolean to my props than the other way around, like this better thanks

**Comment by WebReflection** [comment]
I think I don't want to rush again this change ... I might go back to original implementation which is consistent in both get or set where maybe setting `null` or `undefined` is the only exception that makes sense to remove the attribute, and having a `get booleanAttributes() {}` similar to `observedAttributes` would be way better to handle specific boolean cases.

**Comment by justintaddei** [comment]
This change breaks my app. Anytime someone clears a text input field it is filled with "true"

Which version was this change introduced? I will need to rollback until it is changed or do a lot of refactoring.

**Comment by WebReflection** [comment]
@justintaddei sorry to hear that. The version without this issue is 2.0.2 but I'll push out soon a patch to fix this (soon as in hopefully few hours max)

**Comment by WebReflection** [comment]
FYI v2.2.0 fixed this issue and introduced explicit `get booleanAttributes() { return []; }` at class level.

**Comment by justintaddei** [comment]
Yay! Thank you. I like this approach a lot better.
