### ISSUE TITLE
Basic question on how to use it

### ISSUE THREAD

**Issue by Dacius** [WebReflection/hyperHTML-Element#41]
Can someone please elaborate on how to load this into a browser:

-npm install hyperhtml-element
to use Custom Elements in Node doesn't make any sense to me

-documentation suggest //unpkg.com/hyperhtml@latest/min.js
no HyperHTMLElement there

-Testcase
just loads document-register-element.js

**Comment by WebReflection** [comment]
it's https://unpkg.com/hyperhtml-element
