### ISSUE TITLE
Question: support template element for single file components

### ISSUE THREAD

**Issue by jfbrennan** [WebReflection/hyperHTML-Element#48]
In the docs it states "because behind the scenes hyperHTML uses a template element."

This makes me think it's very possible for HyperHTMLElement to support single file components like Riot and Vue:
```
<!-- Vue -->
<template>
    <p>You're a winner!</p>
    <button v-on:click="dismiss">Close</button>
</template>

<script>
    export default {
        name: 's-alert',
        dismiss() {
            // Tell the parent to remove this child
        }
    }
</script>

<style scoped lang="less">
    p { color: green }
</style>


<!-- Riot -->
<s-alert>
    <p>You're a winner!</p>
    <button onclick="{dismiss}">Close</button>

    <script>
        dismiss() {
            this.unmount();
        }
    </script>

    <style type="text/less">
        :scope p { color: green }
    </style>
</s-alert>
```

Hyper could look like:
```
<template>
    <p>You're a winner!</p>
    <button onclick="dismiss">Close</button>
</template>

<script>
    export default {
        name: 's-alert',
        dismiss() {
            this.remove();
        }
    }
</script>

<style scoped type="text/less">
    p { color: green }
</style>
```

**Comment by WebReflection** [comment]
The `template` is used procedurally to create otherwise invalid nodes. The template tag, as live node, is kinda useless for this library, so please try to understand what is this library, what it does, what it solves, and how to use it, thanks.

**Comment by joshgillies** [comment]
If I'm not mistaken, Vue, Riot, etc all use custom compilers to transform the above into a workable FE component. Which is fundamentally at odds with the philosophy of hyperHTML-Element.
