### ISSUE TITLE
Add link to docs

### ISSUE THREAD

**Issue by jfbrennan** [WebReflection/hyperHTML-Element#52]
I always end up at the repo but need to get here https://viperhtml.js.org/hyperhtml/documentation/#components-2. You should include a link to that in the readme or use the url field

**Comment by k-j-kleist** [comment]
There already is a link to that page, under the heading "Documentation", on the first page of `README.md`.

**Comment by jfbrennan** [comment]
I see it now. Why not just add it to the project url like 99% of repos do :)
