### ISSUE TITLE
Console Error/Rendering Issue in ES5 Test Page

### ISSUE THREAD

**Issue by danmckeon** [WebReflection/hyperHTML-Element#61]
There is an error in the console on the [es5 test page](https://webreflection.github.io/hyperHTML-Element/test/?es5) on Chrome version 76 and the "it worked" link is not rendering.

Error is as follows: 

```
Uncaught TypeError: Failed to construct 'HTMLAnchorElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at MyLink.Intermediate (es5.js?_=0.48887823511286244:2397)
    at new MyLink (test.es5.js?_=0.18174445391217642:154)
```

**Comment by WebReflection** [comment]
You don't need Chrome there, that's a test page for IE

**Comment by danmckeon** [comment]
is there a way to produce code that renders for both modern browsers and IE or does different code need to be served based on browser?

**Comment by danmckeon** [comment]
I've been trying to use Babel but am receiving this error:

```
Uncaught TypeError: Cannot call a class as a function
```

**Comment by WebReflection** [comment]
You need the right transpiler, namely Babel 7

Live example: https://codepen.io/WebReflection/pen/yLBROJK
