### ISSUE TITLE
extending built-in elements with a base class different than HyperHTMLElement doesn't work

### ISSUE THREAD

**Issue by fsodano** [WebReflection/hyperHTML-Element#62]
Hi there!

I think I've come across an issue today, I would like your opinion!

Minimal reproduction:
```html
<!doctype html>
<html lang="en">
<head>
    <script type="text/javascript" src="https://unpkg.com/hyperhtml-element@3.11.0/min.js"></script>
</head>
<body>
<div id="root"></div>

<script type="text/javascript">

    class Base extends HyperHTMLElement{}

    class MyButtonOK extends HyperHTMLElement{
      created() {
        console.log(this.setState); //function :)
      }
    }

    class MyButtonErr extends Base{
      created() {
        console.log(this.setState); //undefined :(
      }
    }

    class StandaloneOk extends Base{
      created() {
        console.log(this.setState); //function :)
      }
    }

    MyButtonOK.define('my-button', {extends: 'button'});
    MyButtonErr.define('my-button-sad', {extends: 'button'});
    StandaloneOk.define('standalone-ok');

  HyperHTMLElement.bind(document.getElementById('root'))`
    <button is="my-button">this.setState is ok</button>
    <button is="my-button-sad">this.setState is undefined</button>
    <standalone-ok>this.setState is ok</standalone-ok>
    `;
</script>
</body>
</html>
```

The problem seems to be in this bit of code: https://github.com/WebReflection/hyperHTML-Element/blob/master/index.js#L2372

I think it's assuming that Super is going to be the HyperHTMLElement class. I got it fixed by including `ownKeys(HyperHTMLElement)`. I'll open a PR in a bit so you can have a look.

Thanks!

**Comment by fsodano** [comment]
Ok, I have created a PR. https://github.com/WebReflection/hyperHTML-Element/pull/63

Please note extending more than 1 class breaks, so I'm going to work on that a bit.

Cheers!

**Comment by fsodano** [comment]
I have updated the PR and now all scenarios (that I could think of) are passing. Please let me know if you have any concerns, @WebReflection!

Thanks.

**Comment by WebReflection** [comment]
Thanks @fsodano, I've left a comment in there, as there's something that could easily break, otherwise it looks good.

**Comment by fsodano** [comment]
Thanks, I've implemented your suggestion and tidied up the code a bit. Cheers!
