### ISSUE TITLE
this.refs is not documented

### ISSUE THREAD

**Issue by jfbrennan** [WebReflection/hyperHTML-Element#64]
`this.refs` seems to be a map of all elements with a `ref` attribute, for example:
```
search() {
  const query = this.refs.search.value; // => "foo"
  ...
} 

render() {
  return this.html`<input ref="search" value="foo">`
}
```
This is a great feature, but I don't see it anywhere in the docs.

**Comment by jfbrennan** [comment]
Closing this because the work should be done in a different project (see PR https://github.com/viperHTML/viperhtml.github.io/pull/34)

**Comment by WebReflection** [comment]
Thanjs for the PR, however that's hyperHTML documentation, which is not necessarily related to this project. This looks like a better hint for the README in here?
