### ISSUE TITLE
double render call on initial element creation

### ISSUE THREAD

**Issue by 2alin** [WebReflection/hyperHTML-Element#71]
`this.render()` is been called two times when the element is initially created. Please check [this demo](https://codepen.io/2alin/pen/RwopZPj). 

There's no issue in subsequent changes of observed attribute values.

**Comment by WebReflection** [comment]
Calling render is super cheap, while avoiding this is super cumbersome. As this should never be a real world issue, in terms of performance, I’m not sure there’s anything to do

**Comment by WebReflection** [comment]
To be fair, if you have an attributes listener the callback is going to be called for *each* attribute change, that’s how custom elements work in platform. If you do anything in attributes callback, such anything would be invoked multiple times. Accordingly, unless you have a better idea on how this should work, I’d close this as won’t fix, as that’s what you get if you call render both in create, and on attributes, which are triggered on custom elements update, one after the other, by specs.

**Comment by 2alin** [comment]
Sounds fair, thanks for clarifying the expected behavior. Feel free to close this issue as you suggested.

**Comment by WebReflection** [comment]
You can reproduce this behavior without any library, which is how specs work, and imho, for a good reason. Hope you don’t mind me closing this, but again, if you have a better idea on how to avoid how specs work, I’m listening 👍
