### ISSUE TITLE
Alternative to `on` prefix for event listeners

### ISSUE THREAD

**Issue by brettz9** [WebReflection/hyperHTML-Element#73]
I'm wondering if, for the sake of preventing potential conflicts, you would consider it helpful to making the "on" prefix convention customizable in some manner (or whether you would just expect such users to rely on `data-call`).

GitHub has [a rule](https://github.com/github/eslint-plugin-custom-elements/blob/main/docs/rules/no-method-prefixed-with-on.md) to prevent use of `on` for custom elements due to the possibility of these global events becoming extended, and it would seem to me to be a reasonable concern (even if it doesn't address `addEventListener` type conflicts). But having a convention such that one could just define methods beginning with `event_` or what not, also seems useful to me.

Maybe not too big of a real world concern, but thought I'd request your thoughts on it.

**Comment by WebReflection** [comment]
![Screenshot from 2021-07-19 08-03-35](https://user-images.githubusercontent.com/85749/126110479-9fa0968a-d775-4380-a162-ab7734ac7dae.png)
