### ISSUE TITLE
suggestion:  include link to https://github.com/WebReflection/hyperHTML in explanation of what this is

### ISSUE THREAD

**Issue by Jeff17Robbins** [WebReflection/hyperHTML-Element#8]
It took me a bit to figure out that the definition of this project

```An extensible class to define hyperHTML based Custom Elements.```

was assuming that the reader would know what `hyperHTML` was.  If that first mention of `hyperHTML` were a link to [hyperHTML](https://github.com/WebReflection/hyperHTML), it would reduce a potential barrier to a newbie interested in the really excellent work you are doing.

**Comment by WebReflection** [comment]
maybe a PR? I'm very busy this evening, sorry

**Comment by Jeff17Robbins** [comment]
Nothing to be sorry about.   I thought it would be helpful to capture the source of my confusion.  I'll get someone at work tomorrow to show me how to submit a PR -- I'm really new at git.

**Comment by WebReflection** [comment]
no progress, will close.
