### ISSUE TITLE
bump hyperhtml dependency

### ISSUE THREAD

**Issue by asapach** [WebReflection/hyperHTML-Element#9]
Is there a reason `hyperhtml` dependency in `package.json` is still at `0.17.x`? Need help updating it to `1.x`?

**Comment by WebReflection** [comment]
no reason in particular, I just haven't had time to go through examples and eventually update them if not working due minor, but breaking, change in v1.

Will keep this open until I find time to do that.

**Comment by WebReflection** [comment]
btw, this module does not ship with hyperHTML, you need to bring it in yourself, so I might actually just get rid of it as dependency and nothing should affect it.

**Comment by WebReflection** [comment]
actually, never mind. If you use npm it does bring it in. Updating now.

**Comment by WebReflection** [comment]
`v0.6` with latest hyperhtml is out.

**Comment by asapach** [comment]
Thanks.
